name: CI/CD Test
on:
  push

jobs:
  test-env-protection:
    runs-on: ubuntu-latest
    outputs:
      ENVI: ${{ steps.set-env.outputs.Environment }}
    steps:    
      - name: Check out code
        uses: actions/checkout@v2        
      - name: Extract latest commit message
        run: |
          echo ${{ github.event.head_commit.message }} 
        
          COMMIT_MESSAGE=${{ github.event.head_commit.message }} | head -n 1
          echo "$COMMIT_MESSAGE"
