name: CI/CD Env Test

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  env-test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
